/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import com.basajans.rest.resource.ConstanConnection;
import com.basajans.wrapper.EmployeeComp;
import com.basajans.wrapper.EmployeeWrapper;
import com.basajans.wrapper.IndividualPerformancePlanTransfer;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.l10n.SimpleDateFormat;
import com.codename1.processing.Result;
import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import com.codename1.ui.util.Resources;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeSet;

/**
 *
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
//    private  List<String> USER_ROLE;
//    private  Form formMain;
//    private Form formHome;
//    private Form formChildDocument;
//    private Form formChildSubordinates;
    public StateMachine(String resFile) {
        super(resFile);
        findLblMessageLogin().setVisible(false);
        
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
        
        
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     * @param res
     */
    @Override
    protected void initVars(Resources res) {
    
    }


    private final ValidasiSession validasiSession=new ValidasiSession();
    private final Map<String,Object> session=new HashMap<>();
    
    @Override
    protected void onMain_BtnLoginAction(Component c, ActionEvent event) {
        String username=findTxtUsername().getText();
        String password=findTxtPassword().getText();
        if(validasiSession.cekfield(username, password)){
            Map<String,String> mapService= new HashMap<>();
            mapService.put("username", username);
            mapService.put("password", password);
            final String payload = Result.fromContent(mapService).toString();
            //http://cloud.abyor.com:13088/hcm/api/login
            ConnectionRequest connectionRequest=new ConnectionRequest("http://cloud.abyor.com:13088/hcm/api/login"){
                 @Override
                    protected void buildRequestBody(OutputStream os) throws IOException {
                            os.write(payload.getBytes("UTF-8"));
                    }

                @Override
                protected void readResponse(InputStream input) throws IOException {
                    JSONParser jsonParse= new JSONParser();
                    Map<String, Object> mapRespone=jsonParse.parseJSON(new InputStreamReader(input));
                    Map<String,Object> mapData=(Map<String,Object>) mapRespone.get("data");
                        if(mapData!=null){
                            session.clear();
                            session.put("username", mapData.get("username"));
                            session.put("auth_token", mapData.get("auth_token")); 
                            loadProfile();
                        }
                
                    }   
            };
            ConstanConnection.postJSON(connectionRequest);
        }else{
            findLblMessageLogin().setText("* please input username and password");
            findLblMessageLogin().setVisible(true);
        }
    }

    @Override
    protected void beforeMainHome(Form f) {
        EmployeeWrapper employeeWrapper=(EmployeeWrapper) session.get("employeeWrapper");
        findLblName().setText(employeeWrapper.getFullName());
        findLblAge().setText(employeeWrapper.getAge().toString());
        findLblUnit().setText(employeeWrapper.getUnit());
        findLblEmpNum().setText(employeeWrapper.getEmployeeNumber());
        findLblPosition().setText(employeeWrapper.getPosition());
    }

    @Override
    protected void beforeMainSubordinates(Form f) {
        ButtonGroup buttonGroup=new ButtonGroup(findRB1(),findRB2(),findRB3(),findRB4());
        findRB1().setSelected(true);
        SimpleDateFormat formatSimple=new SimpleDateFormat("yyyy");
        String year=formatSimple.format(new Date());
        Integer yearNow=Integer.parseInt(year);
        Integer yearNext=yearNow+1;
        Integer yearYester=yearNow-1;
        Integer yearLast=yearNow-2;
        findRB1().setText(yearNext.toString());
        findRB2().setText(year);
        findRB3().setText(yearYester.toString());
        findRB4().setText(yearLast.toString());
        
    }
    
        
    private final Map<String,Object> IPP=new HashMap<>();
    private final Map<String,Object> CAP=new HashMap<>();
    private final Map<String,Object> IPT=new HashMap<>();
    private final Map<String,Object> IPR=new HashMap<>();
    private final TreeSet<EmployeeWrapper> toPartyReportStructure=new TreeSet<>(new EmployeeComp());
    private final TreeSet<EmployeeWrapper> toPartyOrgStructure=new TreeSet<>(new EmployeeComp());
    
    @Override
    protected void postMainSubordinates(Form f) {
        IPP.clear();
        CAP.clear();
        IPT.clear();
        IPR.clear();
        toPartyReportStructure.clear();
        
        ConnectionRequest connectionRequest;
        connectionRequest = new ConnectionRequest("http://cloud.abyor.com:13088/hcm/api/pms/subordinates"){
            @Override
            protected void postResponse() {
            
            }

            @Override
            protected void readResponse(InputStream input) throws IOException {
                JSONParser jsonParse= new JSONParser();
                Map<String, Object> mapRespone=jsonParse.parseJSON(new InputStreamReader(input));
                //Map pertama saat dikirim
                Map<String,Object> mapData=(Map<String,Object>) mapRespone.get("data");
                //mapdata ada data untuk subordiate pada sebuah array list
                ArrayList<Object> items=(ArrayList<Object>) mapData.get("items");
                for (Object object : items) {
                    Map<String,Object> mapItem=(Map<String,Object>) object;
                    if(mapItem.get("structure_type").toString().equals("REPORTING_STRUCTURE")){
                        toPartyReportStructure.add(konversiEmployeeWrapper(mapItem));
                        ArrayList<Object> individualPerformancePlans=(ArrayList<Object>) mapItem.get("individual_performance_plans");
                        IndividualPerformancePlanTransfer individualPerformancePlanTransfer;
                        for (Object individualPPS : individualPerformancePlans) {
                            Map<String,Object> mapindividualPPS=(Map<String,Object>) individualPPS;
                            String number=(mapindividualPPS.get("number")!=null)?mapindividualPPS.get("number").toString():null;
                            individualPerformancePlanTransfer=new IndividualPerformancePlanTransfer();
                            
                        }
                    }else{
                        
                    }
                }
                for (EmployeeWrapper object : toPartyReportStructure) {
                    System.out.println(object.getFullName());
                }
 
            }
        };
        ConstanConnection.GET(connectionRequest, session.get("username").toString(), session.get("auth_token").toString());
    }
    
    private EmployeeWrapper konversiEmployeeWrapper(Map<String,Object> mapItem){
        EmployeeWrapper employeeWrapper;
        employeeWrapper=new EmployeeWrapper();
        employeeWrapper.setId(mapItem.get("id").toString());
        employeeWrapper.setFullName(mapItem.get("full_name").toString());
        employeeWrapper.setPosition(mapItem.get("position").toString());
        employeeWrapper.setStructureType(mapItem.get("structure_type").toString());
        employeeWrapper.setUnit(mapItem.get("unit").toString());
        return employeeWrapper;
    }

    
    
    private void loadProfile() {
         //http://cloud.abyor.com:13088/hcm/api/user/profile
        ConnectionRequest connectionRequest=new ConnectionRequest("http://cloud.abyor.com:13088/hcm/api/user/profile"){

            @Override
            protected void postResponse() {
            }
            
            @Override
            protected void readResponse(InputStream input) throws IOException {
                 JSONParser jsonParse= new JSONParser();
                 Map<String, Object> mapRespone=jsonParse.parseJSON(new InputStreamReader(input));
                 Map<String,Object> mapData=(Map<String,Object>) mapRespone.get("data");
                 EmployeeWrapper employeeWrapper=new EmployeeWrapper();
                 employeeWrapper.setId(mapData.get("id").toString());
                 employeeWrapper.setFullName(mapData.get("full_name").toString()); 
                 String age=mapData.get("age").toString();
                 if(age.length()>0){   
                    employeeWrapper.setAge(Byte.parseByte(age.substring(0, age.length()-2)));
                 }
                 employeeWrapper.setEmployeeNumber(mapData.get("employee_number").toString());
                 employeeWrapper.setPosition(mapData.get("position").toString());
                 employeeWrapper.setUnit(mapData.get("unit").toString());
                 employeeWrapper.setSubareCode(Integer.parseInt(mapData.get("subarea_code").toString()));
                 
                 session.put("employeeWrapper", employeeWrapper);
                 showForm("mainHome", null);
            }
        
        };
        ConstanConnection.GET(connectionRequest, session.get("username").toString(), session.get("auth_token").toString());
    }

   
    
    

    

    @Override
    protected void onMainSubordinates_RB2Action(Component c, ActionEvent event) {
        int index=findList().getModel().getSize();
        for(int i=index-1;i>=0;--i){
            findList().getModel().removeItem(i);
        }
        
        for (EmployeeWrapper employeeWrapper : toPartyReportStructure) {
            findList().addItem(employeeWrapper.getFullName());
        }
    }

    @Override
    protected void onMainSubordinates_RB3Action(Component c, ActionEvent event) {
        int index=findList().getModel().getSize();
        for(int i=index-1;i>=0;--i){
            findList().getModel().removeItem(i);
        }
    }
}
